name: Auto Commit

on:
  schedule:
    - cron: '0 3 * * *'  # Chạy mỗi ngày lúc 3h sáng UTC
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Update timestamp
        run: echo "Auto commit at $(date)" >> log.txt

      - name: Commit changes
        run: |
          git config --global user.email "tastytwinkyyy@gmail.com"
          git config --global user.name "tastytwinkyyy"
          git add .
          git commit -m "Auto commit on $(date)" || echo "No changes to commit"
          git pull --rebase
          git push
